#include "PeopleNotFoundException.hpp"


// const char * MyCustomException::what () { 
//     return message_;
// }

